language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew ":$MODULE:build" ":$MODULE-kotlin:build"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  matrix:
    - MODULE=rxpalette
  global:
    - secure: "nrPJdE/UdDyVBIiTXD+lxKRenqaXgFomWlUGbina1Y5jNYzyUlXwBYC3blzrCSeJsTe7XvPr1iyQAkgdG+IG5HKIPExEvHZUS7mPaKIIEHOEQDlt/2H6Ge2ZH7VJx446pStiZMXj2DYIkoPskVZH7uZ8C85yUFEWZhQ5QZOdo30zUmb2HWsk5kjm/K+WSuF+vUBDuXbAuRHOUJ0j3tqTo0IJxKeIC1AtFfm97fQJK9fIuvc2kLhdge1BkcI+1P28jCedwidmGrcqF+g41PJGNAz61HEfi3HOBcpoS0qIiKYwvcEnBQNjRZ+gDrPUohVqWntJC/rZHmGu0NS3mhEeRXYvn36f8eOYNs392RXmiDUMFlWFtNUd3U0E6P5GobPJI9b9RbaK/lMiyzL5uvBIUNxzXo3i8hBShzlVk4Vk8MyNvMF1bVzpyABEOjMqiPxv9Gc8+ID77t1+iTOpvg6P15AKHUpMi4SsHVRZYAt5JTn0MATK3299/129KLEcvn7csSPhHDMINjNxlhFGgzNjj2Me19irFLbSuATy1NqI93gEgvN0w4PUGU0CeB2JJpkKnmFLj7C21KXCizleCtyovCXwyAe5ypvxy0zW9qssvZ+OdLS71XWy2K/7RLNfEYBP9Qq9xKj2pr361KWUF6aF+Rlj28AjcR6r1/TS1f7mg7A="
    - secure: "IWYmV1voMD/idGmeWTCpq+fps07mSomllOmmMKG/FwdLPu+HdDRLh4awa02J0bdI8bqTW1+MQC/u4IUKfMttp9rE7A+sob1EqmCTFJgpMAJ+VbKfBisnPVG5tVNV1LEkj9Hi8ide6EntOKPDduC9QFonN05xipt+t5slJrRyCo4sPVYByl1Hn1EC4NvZViie7JlB4r+cNaLVHL0JboqLvvbPgdslw6NuaoLYWy2yQr8JZRP3PVWj4jEQ7y+Ek+6V5KTQs62YbyXCETBgeWHm4L6oL7g7nMVWURq5isILZgI7GEHtD5oX+CjOLOgkQkPGyREOLsLDSHw/Ymd96bit2mXyZgSMKNq+Nz3U4kl67hHjMZubmRa3eAdVypM98YeCKfepUf6Wk0PUXPEZplXBG0E12MW5QKi0JkW15WZeVaBxBKMdZJYOyPiVGpMF6A0HxXFrgxRr3TgdB0Dis1hzVuvYQ3gm6WV24mki81FoYwj2XxsgUc+A2hsfuLjC2+1ceabebIdHniJPOjYlFnEdKHimQExCvjIxCpUJ8c0uZkAQlL9zy8hUc6Sx3AjIPsFABwczNxxgD6b5T9o0hOOPOXwHIcTK76xdjtuHnlfMet+cat/GdgOzVpdg2lrVnEXaXk9RbSooAgpaZ2InOZB3vzEqdEXOxCE790GI8EzKsNA="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
