language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18

jdk:
  - oraclejdk8

script:
  - ./gradlew ":$MODULE:build" ":$MODULE-kotlin:build" ":$MODULE:test" ":$MODULE-kotlin:test"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  matrix:
    - MODULE=rxpalette
  global:
    - secure: "LexS8oQASgXChgM2pRjCmVA0Syh+AhoBTMxE5cz3rcDz1TV0jDEpG5eBB2YBHXzoOHCMwvfIfnV+GHSZLbk4Ydsl9w2LOL0pL+RVWKtgNBVpW2khb3auQYA0oUencBcAbDahIaln9J0TqVeh94Wi0gWogikdSp/O6RaHV5sSf89QS4UjVtZJVpRsAiecyD7338R00sBQ2hjEd26rMvA9N2CJ9IVcHthR9dsy4RIwuZEBCJSBb2zsP3ylOPWK85X1sHlw8zV4Q4PNKJVL4kDHp7Ws2yPBLJThwDSw2kjKLBL2L1h/N7ndPxrOjAs704tufzleIaTUV4b3pm+I9A8oQ9tq3unjgi79uiDIg3hgOBPIJRlejEpX17y2eVuiEWucfTRrFkZfAm+vx4PCR/r36mUZwovx7m+y4z23lfM/wkJzZkBLOkMMOBzFxNNnym+5rpSEhAiosIMUDw6ABbbDqldDDiebsPhIFIm5nAJe7QinyIWgK2eHUA/5NvBqqHpx6BXDjHQfbu9h9vff2Omtfpi/PoOyBwYPwQDYqfV1d+95oLtnnN19IsP8yEmBpTH7iI8FKhOZVQC5hI8lDJunpQ8306rOsKPgKlLo3rXLacR/kWvi/99l5D3CTI/h7XI81z6/whEdSjM9tfybbda2lOXw2znv4JJ0v9zNEKgGupk="
    - secure: "JARaLWn8OyofP6JetBv/7yMZdGJg4ILj7iDiRtXmBhCYzpA5X7gLrBuyBNJ0Geao8ooBpn+UJan/LHTASwRNwTyYka44tmkG6uEweFSbt2MRVWC7J6P5rCPxHxH+MxsiXjNq4YFL68o/M/rf8IS8vcMHtS5+PMPqEgUxuNr5c+oOiwmAFndi6WuEMD0E4MLAIpaxFl7DbW/jAktegKYhySF/tsRqgBYlRZFeBFMfBsdG5ZESkGyzpdsDEoyFuofm2DewKC4khGhTqYvzvN7KIx+LFXeCwmnEmc+F9+t5KdJzJtuCrz31gnum8liW9adbYa1CxZG96Cv1rsYSwd3CL3hxAVaLdzT77kJe3S9UMzceXIVNDzePK46SJ7+ZtqQLoGnYdfeJyo++Z0mxoA1uswaA6bJE8YfKhDVRG/F3BdL2IZyCKZZn0Px4lobuw08ieEXG79Dky9BpNBH/HxQjPizbQZVmwriHejacV0Bs+QsdYtsJ8V1rKf5TDer0Rv6SJaAGC01DQaINLfZ6KBECzDqJHIB7d3dHE+uZuO/6VC3kozTYqiPto5CFSTZOjfIyw1O4bwVWoSuoQcqjhmmo4Rb0WFsx+ejVOux6IgNviWTTnB3f6clqbImt6or+vAzsSpKvtd5KNif95tZkk3wIZNo9BYLw8mE9t/ndWgYSYeU="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
